version: '3.8'
services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name : php
    volumes:
      - ./:/var/www/html/LegalOne
    ports:
      - 9000:9000
    working_dir: /var/www/html/LegalOne
    command: bash -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && php-fpm"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name : nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access_log/:/var/log/nginx/
      - ./:/var/www/html/LegalOne
    depends_on:
      - php
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name : elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name : logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logs.log:/tmp/logs.log
#    command:
#      - logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
