controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

ElasticSearchControllers:
    resource: ../src/Modules/LogStatisticsModule/Controllers
    type: annotation
